server:
  port: 8083
logging:
  level: 
    ROOT: WARN
    com.poscoict: TRACE
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
