server:
  port: 8081
logging:
  level: 
    ROOT: WARN
    com.poscoict: TRACE
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
spring:
  application:
    name: sleuth-order-api
  cloud:
    stream:
      bindings:
        input:
          destination: cateringOrder
          content-type: application/json
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      properties:
#        metadata.broker.list: localhost:9092
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web
sample:
  zipkin:
    enabled: true
catering:
  order.base-uri: http://localhost:8081
  payment.base-uri: http://localhost:8082
  stock.base-uri: http://localhost:8083
  delivery.base-uri: http://localhost:8084