server:
  port: 8082
logging:
  level: 
    ROOT: WARN
    com.poscoict: TRACE
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
spring:
  activemq:
    broker-url: tcp://192.168.41.81:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:mysql://192.168.41.81:3306/catering_pass_payment
    username: user.payment
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false
    properties:
      hibernate:
        format_sql:true
