server:
  port: 8084
logging:
  level:
    ROOT: WARN
    com.poscoict: TRACE
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO
spring:
  application:
    name: sleuth-delivery-api
  cloud:
    stream:
      bindings:
        output:
          destination: cateringStock
          content-type: application/json
#        output1:
#          destination: cateringOrder
#          content-type: application/json
#        output2:
#          destination: cateringPayment
#          content-type: application/json
#        output3:
#          destination: cateringStock
#          content-type: application/json
      kafka:
        binder:
          zk-nodes: localhost:2181
          brokers: localhost:9092
#  kafka:
#    producer:
#      bootstrap-servers: localhost:9092
#      properties:
#        metadata:
#          broker:
#            list: localhost:9092
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      type: web
sample:
  zipkin:
    enabled: true
